name: unit-tests-core

on:
  push:
    branches:
      - test-ci
    paths:
      - 'packages/core/**'
  pull_request:
    branches:
      - test-ci
    paths:
      - 'packages/core/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 8.6.6
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build --filter=@afordibot/core
      - run: pnpm test --filter=@afordibot/core

