name: unit-tests-core

on:
  push:
    branches:
      - test-ci
    paths:
      - 'packages/core/**'
  pull_request:
    branches:
      - test-ci
    paths:
      - 'packages/core/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'packages/core'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Run scripts
        run: pnpm install --no-frozen-lockfile
        run: pnpm build
        run: pnpm test

