name: unit-tests-core

on:
  push:
    branches:
      - test-ci
    paths:
      - 'packages/core/**'
  pull_request:
    branches:
      - test-ci
    paths:
      - 'packages/core/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install
      - run: pnpm build --filter=@afordibot/core
      - run: pnpm test --filter=@afordibot/core

